#!/bin/bash
# Script pour créer le repo GitHub et pousser le code

echo "🚀 Création du dépôt GitHub pour Airbnb Agent"
echo ""
echo "⚠️  Le repo n'existe pas encore sur GitHub !"
echo ""
echo "📋 Étapes à suivre :"
echo ""
echo "1. Va sur https://github.com/new"
echo "2. Repository name : airbnb-agent-dashboard"
echo "3. Description : Agent automatisé pour répondre aux demandes Airbnb"
echo "4. Choisis 'Public' (ou Private si tu préfères)"
echo "5. ❌ NE COCHE PAS 'Add a README file'"
echo "6. ❌ NE COCHE PAS 'Add .gitignore'"
echo "7. ❌ NE COCHE PAS 'Choose a license'"
echo "8. Clique sur 'Create repository'"
echo ""
echo "9. Une fois créé, reviens ici et exécute :"
echo ""
echo "   cd /Users/farescrbs/.openclaw/workspace/projects/airbnb-agent"
echo "   git push -u origin main"
echo ""
echo "💡 Astuce : Quand il demande le password, utilise un Personal Access Token"
echo "   (pas ton mot de passe GitHub). Crée-le sur https://github.com/settings/tokens"
echo ""
